name: Test and Build Selected Platforms + Deploy webGL build

on:
  workflow_dispatch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2023.2.5f1
          testMode: playmode
          artifactsPath: test-results
      #Output
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: ./test-results

  buildWebGL:
    name: Build for WebGL
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build WebGL project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./
          unityVersion: 2023.2.5f1
          allowDirtyBuild: true
          buildName: LatestBuild
      # Output
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: WebGLBuild
          path: ./build/WebGL/LatestBuild

  buildWindows:
    name: Build for Windows
    runs-on: windows-latest
    needs: test
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: ./
          unityVersion: 2023.2.5f1
          allowDirtyBuild: true
          buildName: LatestBuild
      # Output
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: WindowsBuild
          path: ./build/StandaloneWindows64

  buildMac:
    name: Build for Mac
    runs-on: macos-latest
    needs: test
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      # Cache
      - uses: actions/cache@v3
        with:
          path: ./Library
          key: Library-${{ hashFiles('./Assets/**', './Packages/**', './ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: ./
          unityVersion: 2023.2.5f1
          allowDirtyBuild: true
          buildName: LatestBuild
      # Output
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: MacBuild
          path: ./build/StandaloneOSX
  #Deploy webGL build
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: buildWebGL
    steps:
      #Download build
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: WebGLBuild
          path: ./build/WebGL/LatestBuild
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/WebGL/LatestBuild
          publish_branch: webGL
